## Global options used to configure multiple charts
##
global:
  rabbitmq:
    auth:
      username: ""
      password: ""

  psql:
    username: ""
    password: ""
    database: ""
    port: 6379

## Artemis-specific options
##
artemis:
  ## asible-vault password to decrypt enrypted configuration files (ssh keys)
  ##
  vaultPassword: ""

  api: {}
  dispatcher: {}
  scheduler: {}
  worker: {}
  periodic_worker: {}

  kerberos:
    enabled: false

postgresql:
  install: true
  extraEnv: []

  metrics:
    enabled: false
    extraEnv: []
    customMetrics: {}

adminer:
  install: false
  extraEnv: []

rabbitmq:
  install: true
  auth:
    username: ""
    password: ""
    erlangCookie: ""
  clustering:
    enabled: false

psql: {}

redis:
  install: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false
  metrics:
    enabled: true
