FROM quay.io/testing-farm/python-ci-image:2022-03-15-5279a64b

RUN    dnf -y update \
    && dnf -y install \
       # required for beaker-client package
       krb5-devel \
       # required for PostgreSQL
       libpq-devel \
       # required for XML libs
       libxml2-devel \
       libxslt-devel \
    && dnf clean all
