FROM quay.io/testing-farm/python-ci-image:2023-05-23-73a71064

RUN    dnf -y update \
    && dnf -y install \
       # required for beaker-client package
       krb5-devel \
       # required for PostgreSQL
       libpq-devel \
       # required for XML libs
       libxml2-devel \
       libxslt-devel \
    && dnf clean all
