---

definitions:
  basic_authentication:
    type: object

    properties:
      username:
        type: string

      tokens:
        type: object

        properties:
          provisioning:
            type: string
          admin:
            type: string

        required:
          - provisioning
          - admin

    required:
      - username
      - tokens

  authentication:
    type: object

    properties:
      method:
        type: string
        enum:
          - basic

      basic:
        "$ref": "#/definitions/basic_authentication"

    required:
      - method

properties:
  artemis_api_url:
    type: string

  artemis_api_version:
    type: string

  provisioning_poll_interval:
    type: number

  authentication:
    "$ref": "#/definitions/authentication"

required:
  - artemis_api_url
  - artemis_api_version
