# source: https://gitlab.com/testing-farm/images/tree/master/python-ci-image
image: quay.io/testing-farm/python-ci-image

stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - wget -O - https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    # Force poetry to create its virtualenvs inside project directory, to avoid complications
    # when trying to leave our current directory when running in Gitlab.
    - poetry config virtualenvs.in-project true

    - cd server && IN_TEST=yes tox -v -e py37

publish_apiary:
  image: "ruby:2.4"

  stage: deploy
  script:
    - gem install apiaryio
    - apiary publish --api-name="artemis6" --path "api/apiary.apib"
  only:
    - master
