= Artemis

*Artemis* is a machine provisioning service. Its goal is to provision a machine - using a set of preconfigured providers as backends - which would satisfy the given hardware and software requirements.

Using REST API, users request provisioning of *guests*, describing the desired hardware and software configuration of each guest. Requests are matched with one or more *pools* - each pool represents one provisioning service like AWS, Azure or private OpenStack instance, each with its own set of available machine setups it can provide - and a machine is acquired from the most suitable pool.

Requests are sorted into several *priority groups* - given that pools may not have infinite resources, some priority groups may be more important than others.

Each provisioning request is asynchronous by its nature: user submits a *guest request* and receives an ID, *guest name*. User then periodically checks status of the request, using the provided ID, until the request becomes ready. From that moment on, the guest is available and reserved for the user. The request can be cancelled at any time, causing release of its resources.

== Environment variables

Artemis expects these environment variables to be specified by the user:

* `ARTEMIS_HOOK_ROUTE` - Routing configuration Python script, called from routing task
* `ARTEMIS_HOOK_AWS_ENVIRONMENT_TO_IMAGE` - Script to map environment to an AWS image, required for `aws` driver
* `ARTEMIS_HOOK_OPENSTACK_ENVIRONMENT_TO_IMAGE` - Script to map environment to an OpenStack image, required for `openstack` driver

These environment variables provide some defaults but can be overridden:

* `ARTEMIS_CONFIG_DIR` - Directory with configuration, by default current working directory
* `ARTEMIS_DB_URL` - SQLalchemy connection string, by default `file://`
* `ARTEMIS_LOG_DB_POOL` - Log events related to database connection pool. Unset by default, use `yes` for INFO-level or `debug` for more details.
* `ARTEMUS_LOG_DB_QUERIES` - Log database queries, by default `no`. Use `yes` value to enable.
* `ARTEMIS_LOG_JSON` - Log output in JSON format, by default `yes`
* `ARTEMIS_SQLALCHEMY_POOL_SIZE` - Connection pool size for postgresql database, by default `20`
* `ARTEMIS_SQLALCHEMY_MAX_OVERFLOW` - Maximum size of connection pool overflow, by default `10`
* `ARTEMIS_VAULT_PASSWORD_FILE` - Password file with Ansible Vault secret, used for decryption

== SSH keys

Artemis uses a single SSH key, called *master key*, to access all guests. This is strictly between Artemis and pools it uses. On top of that, each guest request states what *user key* the guest should be preinstalled on the guest, to make it accessible to the user.

== API

Specification of API is available at https://artemis6.docs.apiary.io/#reference.


== Local development environment

The development environment runs Artemis in https://docs.okd.io/latest/minishift[Minishift] via https://skaffold.dev[Skaffold]. Currently the development environment requires Docker to be installed on the machine, as skaffold uses docker API for building the container images.
Skaffold will redeploy artemis uppon code changes automatically.
Currently, Artemis is not working with latest skaffold, install https://storage.googleapis.com/skaffold/releases/v1.5.0/skaffold-linux-amd6[version 1.5].

=== Install requirements

==== Install Docker

Currently docker is required to run the development environment. Hopefully we can get this workflow working with Podman soon.

[NOTE]
====
If you are running Fedora 31+, where docker does not work out of box, follow this guide to get it working - https://linuxconfig.org/how-to-install-docker-on-fedora-31
====

Follow this guide to install Docker CE on Fedora: https://docs.docker.com/install/linux/docker-ce/fedora/

==== Install Skaffold

Skaffold is a development tool for local Kubernetes development.

To install it follow the following guide: https://skaffold.dev/docs/install/

==== Install Minishift

Minishift is a local Openshift run in a kvm VM on your localhost.

Currently, new version of minishift is not working properly in this use case. Install MiniShift v1.29.0 which is tested.

To install it follow the following guide: https://docs.okd.io/latest/minishift/getting-started/installing.html#installing-manually

To set up the virtualization environment follow the following guide: https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver

Minishift makes requests to the GitHub API to download an image. Sometimes, the GitHub limits the request from IP addresses. To solve this, follow the following guide: https://github.com/minishift/minishift/blob/master/docs/source/troubleshooting/troubleshooting-getting-started.adoc#github-api-rate-limit-exceeded

==== Install Openshift Client Tools

Openshift Client Tools are required to interact with Minishift cluster.

To install them follow the following guide: https://docs.okd.io/1.5/cli_reference/get_started_cli.html#cli-linux

=== Create configuration

Create the Artemis development configuration in the directory 'configuration/' in the project root. Note that the configuration must have a flat
structure without any subdirectories currently.

You can use samples and gen.sh script from configuration/ directory that will setup Artemis to use your existing openstack project.

1. `cp configuration/env.yml.sample configuration/env.yml`
2. Populate `env.yml` file with details of your openstack tenant and ssh key pair to be used by Artemis as master-key.
3. Create an openstack keypair with Artemis public ssh key with selected `openstack_key_name` from `env.yml`. For example,
if `openstack_key_name` is `artemis`:

`openstack keypair create --public-key path/to/artemis.pub artemis`

=== Start the development environment

Start the development environment by sourcing the develop.sh script
+
[source,shell]
....
$ source develop.sh
....
+
The first execution of the script will take some time, as it needs to start Minishift and initially build Artemis.

[NOTE]
====
For change of logging level, use env variable `DEBUG`, for example:
+
[source,shell]
....
$ DEBUG=3 source develop.sh
....
+
====

=== Enable development environment

If you want to interact with minishift where artemis is deployed, you can use the `-s` option while sourcing the `develop.sh` script.
+
[source,shell]
....
$ source develop.sh -s
....
+
This is required only once per terminal session.

=== How to trigger redeployment

If you want to redeploy artemis in the local environment after you made some changes, in the terminal where the `develop.sh` script is sourced press the `enter` key. This is called `manual` deployment trigger and is a bit more sane then the default trigger which redeploys automatically if any of the files changed.

=== Details of local development services

[NOTE]
====
Make sure you have sourced the `develop.sh` script with `-s` option before interacting with minishift via `oc` command.
====

* RabbitMQ Management Console
  * hostname: `oc get route artemis-api`
  * user: guest
  * password: guest

* RabbitMQ Management Console
  * hostname: `oc get route artemis-rabbitmq-management`
  * user: guest
  * password: guest

* PostgreSQL:
  * user: artemis
  * password: artemis
  * database: artemis

[NOTE]
====
If Artemis is killed (e.g. CTRL+C), wait for all pods to be terminated before sourcing develop.sh again.
`oc get pods`
====


== Local development environment without minishift

That is the most lightweight development setup. It spawns rabbitmq, postgresql and redis in docker containers on your
local machine, while Artemis services (api-server, dispatcher and tasks) are launched as daemons by `nominishift-develop.sh`.

[NOTE]
====
You may need to create a separate virtual environment for artemis-cli in case of dependency issues.
====

1. Create virtualenv, activate it and install artemis via pip:
`source .venv/bin/activate && pip install .`

2. The configurations step is identical to the general instruction.

3. Launch rabbitmq, postgresql and redis containers via docker-compose:
`docker-compose up`

4. Start Artemis:
`bash nominishift-develop.sh`

== How to provision a machine

* the best way is to use artemis-cli
* alternatively execute API call via web browser
  * find out API url:`minishift openshift service --url artemis-api`
  * add '_docs' to url and open in browser

[NOTE]
====
If you can't access the provisioned machine by ssh, please check that the security group allows ssh traffic.

(Openstack) To access the vm please use the ssh key you registered as the keypair in your project:
`ssh -i path/to/artemis_private_key user@vm_ip`
====
