= Artemis

*Artemis* is a machine provisioning service. Its goal is to provision a machine - using a set of preconfigured providers as backends - which would satisfy the given hardware and software requirements.

Using REST API, users request provisioning of *guests*, describing the desired hardware and software configuration of each guest. Requests are matched with one or more *pools* - each pool represents one provisioning service like AWS, Azure or private OpenStack instance, each with its own set of available machine setups it can provide - and a machine is acquired from the most suitable pool.

Requests are sorted into several *priority groups* - given that pools may not have infinite resources, some priority groups may be more important than others.

Each provisioning request is asynchronous by its nature: user submits a *guest request* and receives an ID, *guest name*. User then periodically checks status of the request, using the provided ID, until the request becomes ready. From that moment on, the guest is available and reserved for the user. The request can be cancelled at any time, causing release of its resources.

== Environment variables

Artemis expects these environment variables to be specified by the user:

* `ARTEMIS_HOOK_ROUTE` - Routing configuration Python script, called from routing task
* `ARTEMIS_HOOK_AWS_ENVIRONMENT_TO_IMAGE` - Script to map environment to an AWS image, required for `aws` driver
* `ARTEMIS_HOOK_OPENSTACK_ENVIRONMENT_TO_IMAGE` - Script to map environment to an OpenStack image, required for `openstack` driver

These environment variables provide some defaults but can be overridden:

* `ARTEMIS_CONFIG_DIR` - Directory with configuration, by default current working directory
* `ARTEMIS_DB_URL` - SQLalchemy connection string, by default `file://`
* `ARTEMIS_LOG_DB_POOL` - Log events related to database connection pool. Unset by default, use `yes` for INFO-level or `debug` for more details.
* `ARTEMUS_LOG_DB_QUERIES` - Log database queries, by default `no`
* `ARTEMIS_LOG_JSON` - Log output in JSON format, by default `yes`
* `ARTEMIS_SQLALCHEMY_POOL_SIZE` - Connection pool size for postgresql database, by default `20`
* `ARTEMIS_SQLALCHEMY_MAX_OVERFLOW` - Maximum size of connection pool overflow, by default `10`
* `ARTEMIS_VAULT_PASSWORD_FILE` - Password file with Ansible Vault secret, used for decryption

== SSH keys

Artemis uses a single SSH key, called *master key*, to access all guests. This is strictly between Artemis and pools it uses. On top of that, each guest request states what *user key* the guest should be preinstalled on the guest, to make it accessible to the user.

== API

Specification of API is available at https://artemis6.docs.apiary.io/#reference.


== Local development environment

The development environment runs Artemis in https://docs.okd.io/latest/minishift[Minishift] via https://skaffold.dev[Skaffold]. Currently the development environment requires Docker to be installed on the machine, as skaffold uses docker API for building the container images.

=== Install requirements

==== Install Docker

Currently docker is required to run the development environment. Hopefully we can get this workflow working with Podman soon.

[NOTE]
====
If you are running Fedora 31+, where docker does not work out of box, follow this guide to get it working - https://linuxconfig.org/how-to-install-docker-on-fedora-31
====

Follow this guide to install Docker CE on Fedora: https://docs.docker.com/install/linux/docker-ce/fedora/

==== Install Skaffold

Skaffold is a development tool for local Kubernetes development.

To install it follow the following guide: https://skaffold.dev/docs/install/

==== Install Minishift

Minishift is a local Openshift run in a kvm VM on your localhost.

To install it follow the following guide: https://docs.okd.io/latest/minishift/getting-started/installing.html#installing-manually

To set up the virtualization environment follow the following guide: https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver

Minishift makes requests to the GitHub API to download an image. Sometimes, the GitHub limits the request from IP addresses. To solve this, follow the following guide: https://github.com/minishift/minishift/blob/master/docs/source/troubleshooting/troubleshooting-getting-started.adoc#github-api-rate-limit-exceeded

==== Install Openshift Client Tools

Openshift Client Tools are required to interact with Minishift cluster.

To install them follow the following guide: https://docs.okd.io/1.5/cli_reference/get_started_cli.html#cli-linux

=== Create configuration

Create the Artemis development configuration in the directory 'configuration/' in the project root. Note that the configuration must have a flat
structure without any subdirectories currently.

=== Start the development environment

Start the development environment by sourcing the develop.sh script
+
[source,shell]
....
$ source develop.sh
....
+
The first execution of the script will take some time, as it needs to start Minishift and initially build Artemis.

=== Enable development environment

If you want to interact with minishift where artemis is deployed, you can use the `-s` option while sourcing the `develop.sh` script.
+
[source,shell]
....
$ source develop.sh -s
....
+
This is required only once per terminal session.

=== Details of local development services

[NOTE]
====
Make sure you have sourced the `develop.sh` script with `-s` option before interacting with minishift via `oc` command.
====

* RabbitMQ Management Console
  * hostname: `oc get route artemis-api`
  * user: guest
  * password: guest

* RabbitMQ Management Console
  * hostname: `oc get route artemis-rabbitmq-management`
  * user: guest
  * password: guest

* PostgreSQL:
  * user: artemis
  * password: artemis
  * database: artemis

== How to run the WIP version (deprecated)

* create a virtualenv:
+
[source,shell]
....
$ virtualenv -p /usr/bin/python3.7 foo
....
+
* install Artemis:
+
[source,shell]
....
$ pip install --edit .
....
+
* you need a configuration - ping mprchlik for the archive, and unpack it into the repository directory
* initialize sqlite database:
+
[source,shell]
....
$ ARTEMIS_DB_URL="sqlite:///test.db" ARTEMIS_CONFIG_DIR="$(pwd)/artemis-configuration" artemis-init-sqlite-schema
....
+
* check `run.sh` for details, but it should be safe to run as-is
* start it up:
+
[source,shell]
....
$ ./run.sh
....

== How to provision a machine

* execute API call:
+
[source,shell]
....
$ http -j -p HBhb POST "http://127.0.0.1:8001/guests/" keyname='ci-key' environment:='{"arch": "x86_64", "compose": {"openstack": {"image": "RHEL-8.2
.0-x86_64-nightly-latest"}}}' priority_group='default-priority'
POST /guests/ HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 167
Content-Type: application/json
Host: 127.0.0.1:8001
User-Agent: HTTPie/0.9.4

{
    "environment": {
        "arch": "x86_64",
        "compose": {
            "openstack": {
                "image": "RHEL-8.2.0-x86_64-nightly-latest"
            }
        }
    },
    "keyname": "ci-key",
    "priority_group": "default-priority"
}

HTTP/1.1 201 Created
Connection: close
Date: Tue, 19 Nov 2019 11:19:20 GMT
Server: gunicorn/19.9.0
content-length: 280
content-type: application/json; charset=utf-8

{
    "address": null,
    "environment": {
        "arch": "x86_64",
        "compose": {
            "openstack": {
                "image": "RHEL-8.2.0-x86_64-nightly-latest"
            }
        }
    },
    "guestname": "658986d6-118b-41ae-8560-4beadd00be38",
    "owner": "artemis",
    "ssh": {
        "keyname": "ci-key",
        "port": 22,
        "username": "root"
    },
    "state": "pending"
}
....
+
* from now, you may check the progress by checking the state of the request, until you get similar response:
+
[source,shell]
....
$ http -j -p HBhb "http://127.0.0.1:8001/guests/658986d6-118b-41ae-8560-4beadd00be38"
GET /guests/658986d6-118b-41ae-8560-4beadd00be38 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: application/json
Host: 127.0.0.1:8001
User-Agent: HTTPie/0.9.4



HTTP/1.1 200 OK
Connection: close
Date: Tue, 19 Nov 2019 11:21:14 GMT
Server: gunicorn/19.9.0
content-length: 288
content-type: application/json; charset=utf-8

{
    "address": "10.0.132.189",
    "environment": {
        "arch": "x86_64",
        "compose": {
            "openstack": {
                "image": "RHEL-8.2.0-x86_64-nightly-latest"
            }
        }
    },
    "guestname": "658986d6-118b-41ae-8560-4beadd00be38",
    "owner": "artemis",
    "ssh": {
        "keyname": "ci-key",
        "port": 22,
        "username": "root"
    },
    "state": "ready"
}
....
