apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-rabbitmq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-api-log-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.log_storage_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-worker-log-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.log_storage_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-periodic-worker-log-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.log_storage_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-scheduler-log-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.log_storage_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: pvc
  name: {{ .Values.app_name }}-dispatcher-log-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.log_storage_volume_size }}
  storageClassName: {{ .Values.pvc_storage_class }}
