apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: redis
  name: {{ .Values.app_name }}-redis-exporter
spec:
  host: {{ .Values.redis_exporter_hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-redis-exporter
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: rabbitmq
  name: {{ .Values.app_name }}-rabbitmq-management
spec:
  host: {{ .Values.rabbitmq_management_hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-rabbitmq-management
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: rabbitmq
  name: {{ .Values.app_name }}-rabbitmq-exporter
spec:
  host: {{ .Values.rabbitmq_exporter_hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-rabbitmq-exporter
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: postgres
  name: {{ .Values.app_name }}-postgres
spec:
  host: {{ .Values.postgresql_adminer_hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-postgres-adminer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: postgres
  name: {{ .Values.app_name }}-postgres-exporter
spec:
  host: {{ .Values.postgresql_exporter_hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-postgres-exporter
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: api
  name: {{ .Values.app_name }}-api
spec:
  host: {{ .Values.hostname }}
  to:
    kind: Service
    name: {{ .Values.app_name }}-api
