apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: redis
  name: {{ .Values.app_name }}-redis
spec:
  ports:
  - name: {{ .Values.app_name }}-redis
    port: {{ .Values.redis_port }}
    targetPort: {{ .Values.redis_port }}
  selector:
    app: {{ .Values.app_name }}
    component: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: redis
  name: {{ .Values.app_name }}-redis-exporter
spec:
  ports:
  - name: {{ .Values.app_name }}-redis
    port: 80
    targetPort: {{ .Values.redis_exporter_port }}
  selector:
    app: {{ .Values.app_name }}
    component: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: rabbitmq
  name: {{ .Values.app_name }}-rabbitmq
spec:
  ports:
  - name: {{ .Values.app_name }}-rabbitmq
    port: {{ .Values.rabbitmq_port }}
    targetPort: {{ .Values.rabbitmq_port }}
  selector:
    app: {{ .Values.app_name }}
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: rabbitmq
  name: {{ .Values.app_name }}-rabbitmq-exporter
spec:
  ports:
  - name: {{ .Values.app_name }}-rabbitmq
    port: 80
    targetPort: 15692
  selector:
    app: {{ .Values.app_name }}
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: rabbitmq
  name: {{ .Values.app_name }}-rabbitmq-management
spec:
  ports:
  - name: {{ .Values.app_name }}-rabbitmq
    port: {{ .Values.rabbitmq_management_port }}
    targetPort: {{ .Values.rabbitmq_management_target_port }}
  selector:
    app: {{ .Values.app_name }}
    component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: postgres
  name: {{ .Values.app_name }}-postgres
spec:
  ports:
  - name: {{ .Values.app_name }}-postgres
    port: {{ .Values.postgresql_port }}
    targetPort: {{ .Values.postgresql_port }}
  selector:
    app: {{ .Values.app_name }}
    component: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: postgres
  name: {{ .Values.app_name }}-postgres-adminer
spec:
  ports:
  - name: {{ .Values.app_name }}-postgres-adminer
    port: 80
    targetPort: {{ .Values.postgresql_adminer_port }}
  selector:
    app: {{ .Values.app_name }}
    component: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: postgres
  name: {{ .Values.app_name }}-postgres-exporter
spec:
  ports:
  - name: {{ .Values.app_name }}-postgres-exporter
    port: 80
    targetPort: {{ .Values.postgresql_exporter_port }}
  selector:
    app: {{ .Values.app_name }}
    component: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: api
  name: {{ .Values.app_name }}-api
spec:
  ports:
  - port: {{ .Values.api_port }}
    targetPort: {{ .Values.api_target_port }}
  selector:
    app: {{ .Values.app_name }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: api
  name: {{ .Values.app_name }}-api-log-storage
spec:
  ports:
  - name: {{ .Values.app_name }}-api-log-storage
    port: 80
    targetPort: 8081
  selector:
    app: {{ .Values.app_name }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: worker
  name: {{ .Values.app_name }}-worker-log-storage
spec:
  ports:
  - name: {{ .Values.app_name }}-worker-log-storage
    port: 80
    targetPort: 8081
  selector:
    app: {{ .Values.app_name }}
    component: worker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: scheduler
  name: {{ .Values.app_name }}-scheduler-log-storage
spec:
  ports:
  - name: {{ .Values.app_name }}-scheduler-log-storage
    port: 80
    targetPort: 8081
  selector:
    app: {{ .Values.app_name }}
    component: scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    component: dispatcher
  name: {{ .Values.app_name }}-dispatcher-log-storage
spec:
  ports:
  - name: {{ .Values.app_name }}-dispatcher-log-storage
    port: 80
    targetPort: 8081
  selector:
    app: {{ .Values.app_name }}
    component: dispatcher
