---
#
# PosgreSQL deployment
#
# For local development only!
#
# User/database/password are all 'artemis'.
#
apiVersion: v1
kind: Service
metadata:
  name: artemis-postgres
  labels:
    app: artemis
    service: artemis-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: artemis-postgres
  selector:
    service: artemis-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-postgres
spec:
  selector:
    matchLabels:
      service: artemis-postgres
  template:
    metadata:
      labels:
        service: artemis-postgres
    spec:
      containers:
        - name: postgres
          image: centos/postgresql-12-centos7
          env:
            - name: POSTGRESQL_USER
              value: artemis
            - name: POSTGRESQL_PASSWORD
              value: artemis
            - name: POSTGRESQL_DATABASE
              value: artemis
          ports:
            - containerPort: 5432
