global:
  psql:
    username: ""
    password: ""
    host: ""
    port: ""
    database: ""

image:
  registry: quay.io
  repository: testing-farm/artemis
  tag: "v0.0.23"

psql:
  username: ""
  password: ""
  host: ""
  port: 6379
  database: ""

rabbitmq:
  username: ""
  password: ""
  host: ""
  port: ""

redis:
  host: ""
  port: 6379

dbSchemaRevision: ""

configuration:
  users: []
  ssh_keys: []
  priority_groups: []
  guest_tags: {}
  pools: []

vaultPassword: ""

api:
  replicaCount: 1
  port: 8001
  processes: 1
  threads: 1
  resources: {}

dispatcher:
  replicaCount: 1
  resources: {}

scheduler:
  replicaCount: 1
  resources: {}

worker:
  replicaCount: 1
  processes: 1
  threads: 1
  resources: {}

periodic_worker:
  replicaCount: 1
  enabled: false
  processes: 1
  threads: 1
  resources: {}

actor:
  route:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""
  prepare:
    verifySSHRetries: ""
    verifySSHMaxBackoff: ""
  acquire:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""

closeAfterDispatch: "no"

db:
  poolSize: 20
  poolMaxOverflow: 10

logging:
  method: stdout
  level: info
  json: yes
  logDir: ""
  dbPool: no
  dbSlowQueries: no
  dbSlowQueryThreshold: ""
  slowCliCommands: no
  slowCliCommandPattern: ".*"
  slowCliCommandThreshold: ""

kerberos:
  image:
    registry: quay.io
    repository: testing-farm/kerberos
    tag: "latest"

sentry:
  dsn: ""
  baseUrl: ""
