global:
  psql:
    username: ""
    password: ""
    host: ""
    port: ""
    database: ""

image:
  registry: quay.io
  repository: testing-farm/artemis
  tag: "v0.0.23"

psql:
  username: ""
  password: ""
  host: ""
  port: 6379
  database: ""

rabbitmq:
  username: ""
  password: ""
  host: ""
  port: ""

redis:
  host: ""
  port: 6379

dbSchemaRevision: ""

configuration:
  users: []
  ssh_keys: []
  priority_groups: []
  guest_tags: {}
  pools: []

vaultPassword: ""

api:
  replicaCount: 1
  port: 8001
  processes: 1
  threads: 1
  resources: {}

dispatcher:
  replicaCount: 1
  resources: {}

scheduler:
  replicaCount: 1
  resources: {}

workers:
- replicaCount: 1
  processes: 1
  threads: 1
  queues: ""
  resources: {}

actor:
  route:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""
  prepare:
    verifySSHRetries: ""
    verifySSHMaxBackoff: ""
  acquire:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""

connectionCloseAfterDispatch: false

db:
  poolSize: 20
  poolMaxOverflow: 10

logging:
  method: ""
  level: ""
  json: ""
  logDir: ""
  dbPool: ""
  dbSlowQueries: ""
  dbSlowQueryThreshold: ""
  slowCliCommands: ""
  slowCliCommandPattern: ".*"
  slowCliCommandThreshold: ""
  promtailOptions: ""
  promtailUseCustomConfig: false

kerberos:
  image:
    registry: quay.io
    repository: testing-farm/kerberos
    tag: "latest"

sentry:
  dsn: ""
  baseUrl: ""
