global:
  psql:
    username: ""
    password: ""
    host: ""
    port: ""

image: quay.io/testing-farm/artemis:v0.0.22
  #registry: quay.io
  #repository: testing-farm/artemis
  #tag: "v0.0.21"

psql:
  username: ""
  password: ""
  host: ""
  port: 6379
  database: ""

rabbitmq:
  username: ""
  password: ""
  host: ""
  port: ""

redis:
  host: ""
  port: 6379

dbSchemaRevision: ""

configuration:
  users: []
  ssh_keys: []
  priority_groups: []
  guest_tags: {}
  pools: []

vaultPassword: ""

api:
  port: 8001
  processes: 1
  threads: 1

dispatcher: {}

scheduler: {}

worker:
  processes: 1
  threads: 1

periodic_worker:
  enabled: true

  processes: 1
  threads: 1

actor:
  route:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""
  prepare:
    verifySSHRetries: ""
    verifySSHMaxBackoff: ""
  acquire:
    guestRequestRetries: ""
    guestRequestMaxBackoff: ""

closeAfterDispatch: "no"

db:
  poolSize: 20
  poolMaxOverflow: 10

logging:
  method: stdout
  level: info
  json: yes
  logDir: ""
  dbPool: no
  dbSlowQueries: no
  dbSlowQueryThreshold: ""
  slowCliCommands: no
  slowCliCommandPattern: ".*"
  slowCliCommandThreshold: ""

kerberos:
  image:
    registry: quay.io
    repository: testing-farm/kerberos
    tag: "latest"

sentry:
  dns: ""
  baseUrl: ""
