---

version: '2'

services:
  broker:
    hostname: broker
    image: rabbitmq:3

    ports:
      - "5672:5672"

#  api-server:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile.api-server
#    environment:
#      ARTEMIS_BROKER_URL: 'amqp://guest:guest@broker:5672'
#      ARTEMIS_DB_URL: 'sqlite:///DB/test.db'
#      ARTEMIS_CONFIG_DIR: /CONFIG
#    volumes:
#      - ../:/DB:z
#      - ../artemis-configuration:/CONFIG:z
#    ports:
#      - "127.0.0.1:8000:8000"

  dispatcher:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dispatcher
    links:
      - broker
    depends_on:
      - broker
    environment:
      ARTEMIS_BROKER_URL: 'amqp://guest:guest@broker:5672'
      ARTEMIS_DB_URL: 'sqlite:///DB/test.db'
      ARTEMIS_CONFIG_DIR: /CONFIG
    volumes:
      - ../:/DB:z
      - ../artemis-configuration:/CONFIG:z

  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    links:
      - broker
    depends_on:
      - broker
    environment:
      ARTEMIS_BROKER_URL: 'amqp://guest:guest@broker:5672'
      ARTEMIS_DB_URL: 'sqlite:///DB/test.db'
      ARTEMIS_CONFIG_DIR: /CONFIG
      ARTEMIS_VAULT_PASSWORD_FILE: /CONFIG/.vault_pass
    volumes:
      - ../:/DB:z
      - ../artemis-configuration:/CONFIG:z
