version: '3'
services:
  redis:
    image: "docker.io/bitnami/redis:7.4.2"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    network_mode: host

  rabbitmq:
    image: docker.io/library/rabbitmq:3
    ports:
      - "5672:5672"
    network_mode: host

  postgresql:
    image: "docker.io/bitnami/postgresql:17.2.0"
    environment:
      POSTGRESQL_USER: "artemis"
      POSTGRESQL_PASSWORD: "artemis"
      POSTGRESQL_DATABASE: "artemis"
      POSTGRESQL_ADMIN_PASSWORD: "mysecretpassword"
    ports:
      -  "5432:5432"
    network_mode: host
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  prometheus:
    image: "docker.io/bitnami/prometheus:3.0.1"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    network_mode: host
    volumes:
      - ./configuration/prometheus:/etc/prometheus:ro
      - prometheus_data:/opt/bitnami/prometheus/data
    privileged: true

volumes:
  prometheus_data:
  postgresql_data:
