version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbit:
    image: "rabbitmq:3"
    ports:
      - "5672:5672"
  postgres:
    image: "centos/postgresql-12-centos7"
    environment:
      POSTGRESQL_USER: "artemis"
      POSTGRESQL_PASSWORD: "artemis"
      POSTGRESQL_DATABASE: "artemis"
      POSTGRESQL_ADMIN_PASSWORD: "mysecretpassword"
    ports:
      -  "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
