version: '3'
services:
  redis:
    image: "docker.io/bitnamilegacy/redis:7.4.2"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  redis-exporter:
    image: "docker.io/bitnamilegacy/redis-exporter:1.69.0"
    environment:
      REDIS_ADDR: "redis://redis:6379"

  rabbitmq:
    image: "docker.io/bitnamilegacy/rabbitmq:4.0.7"
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: artemis
      RABBITMQ_DEFAULT_PASS: artemis
    volumes:
      - ./configuration/podman-compose/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:Z,ro
      - ./configuration/podman-compose/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:Z,ro

  postgresql:
    image: "docker.io/bitnamilegacy/postgresql:17.4.0"
    environment:
      POSTGRESQL_USERNAME: "artemis"
      POSTGRESQL_PASSWORD: "artemis"
      POSTGRESQL_POSTGRES_PASSWORD: "artemis"
      POSTGRESQL_DATABASE: "artemis"
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "pgaudit,pg_stat_statements"
      # POSTGRESQL_EXTRA_FLAGS: "-c log_statement=all -c log_connections=on -c log_min_messages=INFO"
    ports:
      -  "5432:5432"
    volumes:
      - ./configuration/podman-compose/postgresql/init.sh:/docker-entrypoint-initdb.d/01-init.sh:Z,ro
      - postgresql_data:/var/lib/postgresql/data

  postgresql-exporter:
    image: "docker.io/bitnamilegacy/postgres-exporter:0.17.1"
    environment:
      DATA_SOURCE_NAME: "postgresql://artemis:artemis@postgresql:5432/artemis?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: /tmp/queries.yaml
    volumes:
      - ./configuration/podman-compose/postgresql-exporter/custom-metrics.yaml:/tmp/queries.yaml:Z,ro

  prometheus:
    image: "docker.io/bitnamilegacy/prometheus:3.0.1"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./configuration/podman-compose/prometheus:/etc/prometheus:Z,ro
      - prometheus_data:/opt/bitnami/prometheus/data

volumes:
  prometheus_data:
  postgresql_data:
