= Artemis

*TODO:* server-specific readme belongs here.

*Artemis* is a machine provisioning service. Its goal is to provision a machine - using a set of preconfigured providers as backends - which would satisfy the given hardware and software requirements.

Using REST API, users request provisioning of *guests*, describing the desired hardware and software configuration of each guest. Requests are matched with one or more *pools* - each pool represents one provisioning service like AWS, Azure or private OpenStack instance, each with its own set of available machine setups it can provide - and a machine is acquired from the most suitable pool.

Requests are sorted into several *priority groups* - given that pools may not have infinite resources, some priority groups may be more important than others.

Each provisioning request is asynchronous by its nature: user submits a *guest request* and receives an ID, *guest name*. User then periodically checks status of the request, using the provided ID, until the request becomes ready. From that moment on, the guest is available and reserved for the user. The request can be cancelled at any time, causing release of its resources.

* For environment variables, see https://testing-farm.gitlab.io/artemis/for-admins/environment_variables/
* For metrics, see https://testing-farm.gitlab.io/artemis/for-admins/metrics/

== SSH keys

Artemis uses a single SSH key, called *master key*, to access all guests. This is strictly between Artemis and pools it uses. On top of that, each guest request states what *user key* the guest should be preinstalled on the guest, to make it accessible to the user.

== API

Specification of API is available at https://artemis6.docs.apiary.io/#reference.

== Local development environment

See https://testing-farm.gitlab.io/artemis/docs/content/for-developers/local-development-environment[Local development environment] chapter of our documentation.

== How to provision a machine

* the best way is to use artemis-cli
* alternatively execute API call via web browser
  * find out API url:`minishift openshift service --url artemis-api`
  * add '_docs' to url and open in browser
