---
title: "Local development environment"
date: 2020-10-05T17:09:42+02:00
draft: false
---
:sectlinks:
:showtitle:

[IMPORTANT]
====
The most common environment developers and maintainers of Artemis use is Fedora, of a reasonably recent version, 36+. The "howto" described below is written with respect to this fact, and it is highly likely it would be a bit harder to follow on Debian or other Linux distributions. Please, bear with us.

Any patches to extend this text to non-Fedora realms would be very welcomed.
====

For a development environment, we are using https://docs.docker.com/compose/[Docker Compose] for required services, and run Artemis directly on your workstation. This way we are flexible when making changes, allowing for very quick development. However, it is **not** how Artemis is deployed after all, and in some corner cases, things may behave differently.

[WARNING]
====
This way Artemis source runs in the same environment as the rest of the processes of your workstation. If you do not want to allow that, and you wish to keep Artemis isolated from the rest of your workstation, you may need to acquire a dedicated VM for Artemis development.
====

== Create configuration

First, you will need a configuration for your Artemis server. Create the development configuration in the `server/configuration/` directory.

[NOTE]
====
The configuration must have a flat structure, without any subdirectories.
====

Artemis configuration consists of the main configuration file, `server.yml`, and pool-specific mapping files for translating composes into pool images.

* prepare an SSH keypair for Artemis. Instead of creating new pair, you may wish to use an existing one if you are not starting from the scratch, but rather work with already existing keys and prepared tenants. In any case, the SSH key must be configured in cloud tenants you plan to use for VMs to be spawned with the said key.
+
* copy `server.yml.samle` to `server.yml`, and edit it. Comment out example pools you do not wish to use, and fill in the blanks, namely credentials and SSH keys.
* create a file named `configuration/.vault_pass` and store a string in it. The string would be used by Artemis to encrypt sensitive fields in its database. It will remain completely local to your configuration, it will not be shared with anyone else.


== Create development environment

This is the most lightweight development setup: it spawns the necessary requirements - RabbitMQ, PostgreSQL and Redis - in Docker containers on your workstation, while Artemis services - API server, dispatcher, scheduler and workers - are launched as daemons.

[NOTE]
====
Artemis server and its CLI tool, `artemis-cli`, exist as separate projects in this repository. Each has its own requirements, and you have to install them as such. We are using https://python-poetry.org/[Poetry] to manage installations.
====

* Artemis service lives in `server` directory:
+
[source,shell]
....
$ cd server/
....
+
* create a local installation of Artemis:
+
[source,shell]
....
$ make install
....
+
[NOTE]
====
You may be interested in a lighter installation, without tools like linters and similar development tools:

[source,shell]
....
$ make install-no-dev
....

This method is good for running Artemis locally, less packages installed and less disk space used, but it's not very well suited for creating patches as it lacks some useful development tools, see <<_follow_up_steps>>.
====
+
* follow the <<_create_configuration>> instructions.
* launch RabbitMQ, PostgreSQL and Redis containers:
+
[source,shell]
....
$ docker-compose up
....
+
[TIP]
====
Add `-d` option to run containers in _detached_ mode, i.e. in the background:

[source,shell]
....
$ docker-compose up -d
....
====
+
* start Artemis:
+
[source,shell]
....
$ ./run.sh
....
+
* To stop Artemis, use the well-known `Ctrl+C` combination.
* To stop the RabbitMQ, PostgreSQL and Redis containers, either use `Ctrl+C` as well, or, if you started them in a detached mode, use `docker-compose`:
+
[source,shell]
....
$ docker-compose down
....
+
[TIP]
====
In case you want to remove the persistent storage of PostgreSQL and RabbitMQ containers, use the `-v` option:

[source,shell]
....
$ docker-compose down -v
....

This instructs Docker to remove volumes associated with the containers.
====

=== Environment variables

Besides xref:environment-variables.adoc[the variables accepted by Artemis itself], the `nominishift-develop.sh` accepts additional variables:

* `ONLY_DB_INIT`: When set to any value, the `run.sh` script would perform the database initialization and quit immediately after that, without running any Artemis components.
* `SKIP_DB_INIT`: When set to any value, the `run.sh` script would skip the database initialization.


== Follow-up steps

After you complete the setup of your local development environment, there are additional steps to complete the whole process and make your environment ready for future development.

=== Install development tools

Artemis packaging points to several tools that can help with the development and testing of your patches - `pre-commit`, linters.

[WARNING]
====
Technically, you do not need to install these tools to develop Artemis patches. However, some of them are mandatory part of Gitlab CI process testing each submitted patch (`pre-commit`) and other can be very helpful when integrated with your IDE (`mypy`, `flake8`, etc.).
====

[NOTE]
====
You do not need to install these tools to run the test suite - test suite takes care of installing its requirements as needed and does not depend on this step.
====

[NOTE]
====
If you used the recommended `make install` command from above, you already do have these tools ready to use. However, if you opted for `make install-no-dev`, Artemis server installation lacks the development tools.
====

* install pre-commit hook:
+
[source,shell]
....
$ poetry run pre-commit install
....

To integrate the tools with your IDE, you will need provide IDE with path to the virtual environment managed by Poetry. Run following command:

[source,shell]
....
$ poetry env info

Virtualenv
Python:         3.7.7
Implementation: CPython
Path:           /foo/bar/artemis/server/.venv <1>
Valid:          True
...
....
<1> this is the path you are looking for.

Then follow your IDE's documentation - it is often possible to point the IDE to particular linters by their path, e.g. `/foo/bar/artemis/server/.venv/bin/mypy`.
