"""
Add shelving support

Revision ID: 23acf56cffe4
Revises: 9844f8f59644
Create Date: 2021-07-25 19:44:06.984653

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '23acf56cffe4'
down_revision = '9844f8f59644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shelves',
        sa.Column('shelfname', sa.String(), nullable=False),
        sa.Column('ownername', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['ownername'], ['users.username'], ),
        sa.PrimaryKeyConstraint('shelfname')
    )

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelfname', sa.String(), nullable=True))
        batch_op.create_foreign_key('shelfname', 'shelves', ['shelfname'], ['shelfname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shelfname')

    op.drop_table('shelves')
    # ### end Alembic commands ###
