"""
Add custom in-pool guest "label" aka instance name

Revision ID: 23bbd5dab7de
Revises: 4066bcbc54eb
Create Date: 2021-04-09 21:49:16.713496

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '23bbd5dab7de'
down_revision = '4066bcbc54eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_label', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('pool_label')

    # ### end Alembic commands ###
