# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add guest_events.guestname/updated index

Revision ID: 261f53f52b83
Revises: 54744e9a5aaf
Create Date: 2025-01-20 11:13:28.379310

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '261f53f52b83'
down_revision = '54744e9a5aaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_guest_events_guestname_updated'), ['guestname', sa.text('updated ASC')], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_events_guestname_updated'))

    # ### end Alembic commands ###
