# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Adding pool resources metrics table

Revision ID: 2a205a7d6150
Revises: 487f52cc5aef
Create Date: 2020-09-15 14:11:27.472692

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '2a205a7d6150'
down_revision = '487f52cc5aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        poolresourcesmetricsdimensions_enum = postgresql.ENUM(
            'LIMITS', 'USAGE',
            name='poolresourcesmetricsdimensions',
            create_type=True
        )

    else:
        poolresourcesmetricsdimensions_enum = sa.Enum('LIMITS', 'USAGE', name='poolresourcesmetricsdimensions')

    op.create_table(
        'metrics_pool_resources',
        sa.Column('poolname', sa.String(length=250), nullable=False),
        sa.Column('dimension', poolresourcesmetricsdimensions_enum, nullable=False),
        sa.Column('instances', sa.BigInteger(), nullable=True),
        sa.Column('cores', sa.BigInteger(), nullable=True),
        sa.Column('memory', sa.BigInteger(), nullable=True),
        sa.Column('diskspace', sa.BigInteger(), nullable=True),
        sa.Column('snapshots', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('poolname', 'dimension')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics_pool_resources')

    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TYPE poolresourcesmetricsdimensions;")

    # ### end Alembic commands ###
