"""
Adding pool resources metrics table

Revision ID: 2a205a7d6150
Revises: 487f52cc5aef
Create Date: 2020-09-15 14:11:27.472692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a205a7d6150'
down_revision = '487f52cc5aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metrics_pool_resources',
        sa.Column('poolname', sa.String(length=250), nullable=False),
        sa.Column('dimension', sa.Enum('LIMITS', 'USAGE', name='poolresourcesmetricsdimensions'), nullable=False),
        sa.Column('instances', sa.BigInteger(), nullable=True),
        sa.Column('cores', sa.BigInteger(), nullable=True),
        sa.Column('memory', sa.BigInteger(), nullable=True),
        sa.Column('diskspace', sa.BigInteger(), nullable=True),
        sa.Column('snapshots', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('poolname', 'dimension')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics_pool_resources')
    # ### end Alembic commands ###
