"""
Adds knobs table

Revision ID: 2f06732734fa
Revises: 8c470c3f4331
Create Date: 2020-09-23 23:50:48.049562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f06732734fa'
down_revision = '8c470c3f4331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'knobs',
        sa.Column('knobname', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('knobname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knobs')
    # ### end Alembic commands ###
