"""
Refactor metrics table

Revision ID: 48609a3f5d7a
Revises: 8c470c3f4331
Create Date: 2020-10-02 15:38:06.976919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48609a3f5d7a'
down_revision = '8c470c3f4331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metrics_failover',
        sa.Column('from_pool', sa.String(length=250)),
        sa.Column('to_pool', sa.String(length=250)),
        sa.Column('count', sa.Integer()),
        sa.Column('updated', sa.DateTime()),
        sa.ForeignKeyConstraint(['from_pool'], ['pools.poolname'], ),
        sa.ForeignKeyConstraint(['to_pool'], ['pools.poolname'], ),
        sa.PrimaryKeyConstraint('from_pool', 'to_pool')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_column('_id')
        batch_op.add_column(sa.Column('metric', sa.String(length=250), nullable=False))
        # Adding a primary_key=True in table definition isn't reflected by Alembic,
        # it's not going to create a corresponding index.
        batch_op.create_primary_key('ix_metrics_metric', ['metric'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_id', sa.INTEGER()))
        batch_op.drop_constraint('ix_metrics_metric')
        batch_op.drop_column('metric')

    op.drop_table('metrics_failover')
    # ### end Alembic commands ###
