# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add task sequence requests

Revision ID: 54744e9a5aaf
Revises: 56597d9c983a_4
Create Date: 2025-01-03 14:44:37.644329

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '54744e9a5aaf'
down_revision = '56597d9c983a_4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task_sequence_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('task_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_sequence_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_task_requests_task_sequence_requests_id',
            'task_sequence_requests',
            ['task_sequence_request_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_requests_task_sequence_requests_id', type_='foreignkey')
        batch_op.drop_column('task_sequence_request_id')

    op.drop_table('task_sequence_requests')
    # ### end Alembic commands ###
