# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Upgrade to SQLAlchemy 2.0

Revision ID: 56597d9c983a
Revises: e5e1011ec6c2
Create Date: 2024-11-13 11:37:41.404810

"""
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision = '56597d9c983a'
down_revision = 'e5e1011ec6c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.alter_column(
            'updated',
            existing_type=sa.DATETIME(),
            nullable=False
        )

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.alter_column(
            '_on_ready',
            existing_type=sqlite.JSON(),
            nullable=False
        )

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column(
            'count',
            existing_type=sa.INTEGER(),
            nullable=False
        )
        batch_op.alter_column(
            'updated',
            existing_type=sa.DATETIME(),
            nullable=False
        )

    with op.batch_alter_table('sshkeys', schema=None) as batch_op:
        batch_op.alter_column(
            'enabled',
            existing_type=sa.BOOLEAN(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sshkeys', schema=None) as batch_op:
        batch_op.alter_column(
            'enabled',
            existing_type=sa.BOOLEAN(),
            nullable=True
        )

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column(
            'updated',
            existing_type=sa.DATETIME(),
            nullable=True
        )
        batch_op.alter_column(
            'count',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.alter_column(
            '_on_ready',
            existing_type=sqlite.JSON(),
            nullable=True
        )

    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.alter_column(
            'updated',
            existing_type=sa.DATETIME(),
            nullable=True
        )

    # ### end Alembic commands ###
