# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Upgrade to SQLAlchemy 2.0 - guest_requests

Revision ID: 56597d9c983a_2
Revises: 56597d9c983a_1
Create Date: 2024-11-13 11:37:41.404810

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '56597d9c983a_2'
down_revision = '56597d9c983a_1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.alter_column(
            '_on_ready',
            existing_type=sqlite.JSON(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.alter_column(
            '_on_ready',
            existing_type=sqlite.JSON(),
            nullable=True
        )

    # ### end Alembic commands ###
