# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add pool tags table

Revision ID: 63866e38fe0b
Revises: b9963fb2b987
Create Date: 2025-10-30 10:13:00.013173

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '63866e38fe0b'
down_revision = 'b9963fb2b987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pool_tags',
        sa.Column('poolname', sa.String(), nullable=False),
        sa.Column('tag', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('poolname', 'tag'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pool_tags')
    # ### end Alembic commands ###
