# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add guest_request.guestname/poolname index

Revision ID: 89f347ae4345
Revises: 261f53f52b83
Create Date: 2025-03-12 16:13:17.853279

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '89f347ae4345'
down_revision = '261f53f52b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.create_index('ix_guestname_poolname', ['guestname', 'poolname'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_guestname_poolname')

    # ### end Alembic commands ###
