"""
Adds guest_requests.ctime

Revision ID: 8f7a33b3e529
Revises: edbe5a51f52a
Create Date: 2021-02-03 14:45:59.275145

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '8f7a33b3e529'
down_revision = 'edbe5a51f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'ctime',
            sa.DateTime(),
            nullable=False,
            # See db.py, `guest_requests.ctime` for details on why `server_default` is a string here,
            # and not a function.
            server_default=str(datetime.datetime.utcnow())
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('ctime')

    # ### end Alembic commands ###
