"""
Convert Text to JSON

Revision ID: 98d303ec4630
Revises: b4857538ddf3
Create Date: 2021-01-05 19:21:47.948005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d303ec4630'
down_revision = 'b4857538ddf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_details', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.execute('UPDATE guest_events SET _details = details_serialized')

        batch_op.drop_column('details_serialized')

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_environment', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('_pool_data', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('_user_data', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.execute('UPDATE guest_requests SET _environment = environment')
        batch_op.execute('UPDATE guest_requests SET _pool_data = pool_data')
        batch_op.execute('UPDATE guest_requests SET _user_data = user_data')

        batch_op.drop_column('pool_data')
        batch_op.drop_column('user_data')
        batch_op.drop_column('environment')

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_parameters', sa.JSON(), nullable=False, server_default='{}'))

    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.execute('UPDATE pools SET _parameters = parameters')

        batch_op.drop_column('parameters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameters', sa.TEXT(), nullable=False))
        batch_op.drop_column('_parameters')

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('user_data', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('pool_data', sa.TEXT(), nullable=False))
        batch_op.drop_column('_user_data')
        batch_op.drop_column('_pool_data')
        batch_op.drop_column('_environment')

    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_serialized', sa.TEXT(), nullable=True))
        batch_op.drop_column('_details')

    # ### end Alembic commands ###
