# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""Adding guest_requests.user_data column

Revision ID: a3c173dfd6f5
Revises: 57f5d41c7200
Create Date: 2020-09-09 15:46:08.082626

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a3c173dfd6f5'
down_revision = '57f5d41c7200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('user_data')
    # ### end Alembic commands ###
