"""Adding user_data table

Revision ID: a3c173dfd6f5
Revises: 57f5d41c7200
Create Date: 2020-09-09 15:46:08.082626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c173dfd6f5'
down_revision = '57f5d41c7200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_requests', sa.Column('user_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_requests', 'user_data')
    # ### end Alembic commands ###
