"""
Rename guest_events.details

Revision ID: b4857538ddf3
Revises: edbe5a51f52a
Create Date: 2020-12-31 11:16:01.011241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4857538ddf3'
down_revision = 'edbe5a51f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_serialized', sa.Text(), nullable=True))

    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.execute('UPDATE guest_events SET details_serialized = details')
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))

    with op.batch_alter_table('guest_events', schema=None) as batch_op:
        batch_op.execute('UPDATE guest_events SET details = details_serialized')
        batch_op.drop_column('details_serialized')

    # ### end Alembic commands ###
