# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
adds-task-request-table

Revision ID: cbb792480f16
Revises: cf1a39506196
Create Date: 2022-04-23 23:35:43.348556

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cbb792480f16'
down_revision = 'cf1a39506196'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('taskname', sa.Text(), nullable=False),
        sa.Column('arguments', sa.JSON(), nullable=False),
        sa.Column('delay', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_requests')
    # ### end Alembic commands ###
