# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add guest request with pool data

Revision ID: d4a6a1fb98fe
Revises: 89f347ae4345
Create Date: 2025-04-09 10:05:37.468780

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4a6a1fb98fe'
down_revision = '89f347ae4345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_pool_data', sa.JSON(), server_default='{}', nullable=False))
        batch_op.drop_column('pool_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_data', sa.TEXT(), nullable=False))
        batch_op.drop_column('_pool_data')

    # ### end Alembic commands ###
