# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add guest request with pool data

Revision ID: d4a6a1fb98fe
Revises: 89f347ae4345
Create Date: 2025-04-09 10:05:37.468780

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4a6a1fb98fe'
down_revision = '89f347ae4345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        if op.get_bind().dialect.name == 'postgresql':
            batch_op.add_column(sa.Column('_pool_data', postgresql.JSONB(), server_default='{}', nullable=False))

        else:
            batch_op.add_column(sa.Column('_pool_data', sa.JSON(), server_default='{}', nullable=False))

    if op.get_bind().dialect.name == 'postgresql':
        op.get_bind().execute(
            sa.text(
                """
                UPDATE guest_requests
                SET _pool_data = jsonb_build_object(poolname, pool_data::jsonb)::json
                WHERE poolname IS NOT NULL
                """
            )
        )

    else:
        op.get_bind().execute(
            sa.text(
                """
                UPDATE guest_requests
                SET _pool_data = json_object(poolname, pool_data)
                WHERE poolname IS NOT NULL
                """
            )
        )

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('pool_data')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool_data', sa.TEXT(), server_default='{}', nullable=False))

    if op.get_bind().dialect.name == 'postgresql':
        op.get_bind().execute(
            sa.text(
                """
                UPDATE guest_requests
                SET pool_data = jsonb_extract_path(_pool_data, poolname)::text
                WHERE poolname IS NOT NULL
                """
            )
        )

    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('_pool_data')

    # ### end Alembic commands ###
