"""User data shall never be NULL

Revision ID: e330c79c8189
Revises: a3c173dfd6f5
Create Date: 2020-09-13 08:40:14.269264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e330c79c8189'
down_revision = 'a3c173dfd6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'guest_requests',
        'user_data',
        existing_type=sa.TEXT(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'guest_requests',
        'user_data',
        existing_type=sa.TEXT(),
        nullable=True
    )
    # ### end Alembic commands ###
