# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add guest log blob content hash

Revision ID: e5e1011ec6c2
Revises: 275f45109b5c
Create Date: 2024-11-01 10:58:33.213579

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e5e1011ec6c2'
down_revision = '275f45109b5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_log_blobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_log_blobs', schema=None) as batch_op:
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
