# Copyright Contributors to the Testing Farm project.
# SPDX-License-Identifier: Apache-2.0

"""
Add GuestRequest.last_poolname to hold the last poolname after failed provision attempts

Revision ID: ec3239807678
Revises: 3082955b6723
Create Date: 2023-08-24 13:39:14.439959

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec3239807678'
down_revision = '3082955b6723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_poolname', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_requests', schema=None) as batch_op:
        batch_op.drop_column('last_poolname')

    # ### end Alembic commands ###
