{{- if not (include "artemis.psql.useExistingSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artemis.psql.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresql-password: {{ pluck "password" .Values.psql .Values.global.psql |
                          first | b64enc | quote }}
---
{{- end }}

{{- if not (include "artemis.rabbitmq.useExistingSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artemis.rabbitmq.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rabbitmq-password: {{ pluck "password" .Values.rabbitmq
                          .Values.global.rabbitmq.auth |
                        first | b64enc | quote }}
---
{{- end }}
