---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "artemis-core.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{
    (.Files.Glob (printf "%s/*" .Values.artemis.configDir)).AsConfig |
    nindent 2
  }}
