---
title: "AWS driver"
date: 2022-01-05T16:24:28+01:00
draft: false
---
:sectlinks:
:showtitle:

== AWS

=== Image filters

When searching for images, AWS driver would list all images owned by the `self` owner, i.e. it is limited by images owned by the given credentials.
This can be a substantial amount of images, especially when pool has access to public catalogs, and large number of images may considerably extend the time needed to acquire necessary information from AWS API and increase resource usage.
To expand the set of possible owners while limiting the amount of cached images, it is possible to employ several image filters.

Each entry of `image-filters` list may enable multiple filters at once, they all must match the image for it to be included in the cache.
All filters are optional, but at least one must be enabled.

Filters are applied in groups:

1. `name-wildcard` and `owner` are applied first, being passed to AWS CLI `describe-images` command
2. `name-regex`, `max-age` and `creation-date-regex` are applied second, pruning the list acquired from `describe-images` even further.

.Specification
[source,yaml]
....
image-filters:
    # Image name must match a glob-like string
  - name-wildcard: <wildcard string>

    # Image name must match a regular expression
    name-regex: <pattern>

    # Image owner must match
    owner: <string>

    # Image must be younger than this many seconds
    max-age: <integer>

    # Image creation date must match a regular expression.
    # The date would be in the following format: "2019-05-10T13:17:12.000Z"
    creation-date-regex: <pattern>
....

.Example
[source,yaml]
....
image-owners:
  # Include all images we own
  - owner: "self"

  # From this owner, pick only CentOS Stream images
  - owner: "123456"
    name-wildcard: "CentOs Stream *"

  # From this owner, pick only images created in November or December
  - owner: "654321"
    creation-date-regex: "2023-(11|12)-.*"
....

[NOTE]
====
Wildcard paterns accepted by `image-filters` are an exception to Artemis prefering regular expressions when working with patterns.
These patterns are not regular expressions, they will be passed to AWS CLI's `--filter` option which accepts glob-like wildcards only.
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI[AWS EC2 documentation] for more details on filters.
====

=== Security Groups

AWS instances require security groups to control network access. Artemis supports two approaches:

==== Pool-level Security Groups

You can specify one or more security groups that will be attached to all instances in the pool:

.Single security group
[source,yaml]
....
security-group: "sg-12345678"
....

.Multiple security groups
[source,yaml]
....
security-group:
  - "sg-12345678"
  - "sg-87654321"
....

==== Guest-specific Security Groups

Alternatively, you can let Artemis create a dedicated security group for each guest with custom rules:

[source,yaml]
....
create-security-group-per-guest: true

security-group-rules:
  - type: ingress
    protocol: tcp
    port: "22"
    cidr:
      - "10.0.0.0/8"
  - type: egress
    protocol: "-1"
    port: "-1"
    cidr:
      - "0.0.0.0/0"
....

When using `create-security-group-per-guest: true`, if you also specify `security-group`, both the pool-level security group(s) and the guest-specific security group will be attached to the instance.

=== Expose Public IP address

By default, Artemis will expose the private IP address of the instance. In case you want to rather expose the public IP, use the `use-public-ip` setting in the pool configuration.

.Example
[source,yaml]
....
use-public-ip: true
....

=== Console access

AWS driver supports both interactive console (URL) and console log (blob) access. For details on console support across all drivers, see <<drivers.adoc#_console_support_details,"Console support details">>.

==== Console log

Console log is retrieved via the AWS `get-console-output` API.

[NOTE]
====
AWS limits console output to the most recent 64 KB. Older output is not available through this API.
====

==== Interactive console

Interactive console uses AWS EC2 Instance Connect. The console URL template can be customized:

.Environment variable
....
ARTEMIS_AWS_LOGS_CONSOLE_INTERACTIVE_URL
....

.Default value
....
https://console.aws.amazon.com/ec2/v2/connect/ec2-user/{instance_id}?connection-type=isc&serial-port=0
....

[NOTE]
====
Interactive console is only available on instances with ENA (Elastic Network Adapter) support. When a guest requests `console:interactive` with URL content type, flavors without ENA support are automatically filtered out.
====
