---
title: "Beaker driver"
date: 2021-12-13T23:30:02+01:00
draft: false
---
:sectlinks:
:showtitle:

== Beaker

=== Credentials

When Beaker access is protected by authentication, driver can be configured to include credentials when talking to its backend.

.Specification
[source,yaml]
....
username: <string>
password: <string>
....

.Example
[source,yaml]
....
username: a-beaker-username
password: corresponding-password
....

[NOTE]
====
Both `username` and `password` are required when any of these two is used - driver expects either no explicit credentials, or both username and password to be given.
====

=== Beaker groups

To avoid provisioning machines owned by particular Beaker groups, driver can be configured to avoid them.

.Specification
[source,yaml]
....
avoid-groups:
  - group-1
  - group-2
  ...
....

.Example
[source,yaml]
....
avoid-groups:
  # While our Beaker account has access to these groups, don't provision machines owned by them.
  - special-gpus
  - laptops
....

Each provisioning Beaker job would then contain two sets of elements to implement this behavior:

* `<group op="!=" value="$groupname"/>` to instruct Beaker to avoid this group,
* `<hostname op="!=" value="$hostname"/>` to instruct Beaker to avoid machines *owned* by these groups.

The list of machines owned by each group is cached, updated periodically by querying Beaker API.

[NOTE]
====
For more notes on how drivers query their backends, see <<drivers.adoc#_collection_of_information,"Collection of information">>.
====

[NOTE]
====
`avoid-hostnames` and `avoid-groups` are fully compatible, and can be used together.
====

[TIP]
====
It is possible to configure multiple pools for the same set of Beaker credentials, each with different `avoid-groups` list. For example:

[source,yaml]
....
# pool #1
avoid-groups:
  - laptops

# pool #2
avoid-groups:
  - generic-group-owning-machines-not-owned-by-any-other-group
....

This way, common guest requests can be routed to pool #1, while requests in the need of a special laptop HW would be routed to pool #2.
====

=== Beaker hostnames

To avoid provisioning particular machines, driver can be configured to avoid them.

.Specification
[source,yaml]
....
avoid-hostnames:
  - hostname-1
  - hostname-2
  ...
....

.Example
[source,yaml]
....
avoid-hostnames:
  # The following machines are not to be used for day-to-day jobs.
  - some.valuable.machine.com
  # This is a special laptop we do not want to use at all.
  - big-boss.foo.com
....

Each provisioning Beaker job would then contain a set of `<hostname/>` elements to instruct Beaker to avoid the listed machines.

[NOTE]
====
`avoid-hostnames` and `avoid-groups` are fully compatible, and can be used together.
====

[TIP]
====
It is possible to configure multiple pools for the same set of Beaker credentials, each with different `avoid-hostnames` list. For example:

[source,yaml]
....
# pool #1
avoid-hostnames:
  - fancy1.foo.com
  - fancy2.foo.com

# pool #2
avoid-hostnames:
  # Can use fancyN machines, but...
  - not-so-fancy1.foo.com
  - not-so-fancy2.foo.com
....
====

=== Beaker pools

A pool can be pinned to use only a specific subset of Beaker machines by requesting them to belong to one or more Beaker pools.

[NOTE]
====
Artemis pool is not equivalent to Beaker pool. Beaker pools are internal to Beaker, a way of access management, and a single Artemis pool can be configured to provision machines belonging to different Beaker pools.
====

.Specification
[source,yaml]
....
pools:
  - poolname-1
  - poolname: poolname-2
  - poolname: poolname-3
    system-type: system-type-1
  ...
....

.Example
[source,yaml]
....
pools:
  # Provision machines belonging to the following Beaker pools.
  - some-pool
  - another-pool
  - poolname: yet-another-pool
  # Same but with this pool, we need to use different system type for provisioning.
  - poolname: custom-laptops
    system-type: Laptop
....

Each provisioning Beaker job would then contain a set of `<pool/>` elements, with `<system_type/>` as needed, to instruct Beaker to pick only machines from specified pools.

[TIP]
====
It is possible to configure multiple pools for the same set of Beaker credentials, each with different `pools` list. For example:

[source,yaml]
....
# pool #1
pools:
  - some-pool

# pool #2
pools:
  - some-pool
  # Can use fancy machines as well!
  - pool-with-very-fancy-machines
....
====


=== Distro variants

A compose can be mapped to a particular distro variant, ``Server``, ``Workstation`` or any other offered by the distro. By default, no specific variant is requested from Beaker.

.Specification
[source,yaml]
....
- 'compose1':          'distro1'
- 'compose1-Variant1': 'distro1;variant=Variant1'
- 'compose1-Variant2': 'distro1;variant=Variant2'
....

.Example
[source,yaml]
....
# Basic mapping for Fedora Rawhide, Beaker will pick the default variant for us.
- 'Fedora-Rawhide': 'Fedora-Rawhide'
# For users interested in a particular variant, prepare composes with precise mapping.
- 'Fedora-Rawhide-Server': 'Fedora-Rawhide;variant=Server'
- 'Fedora-Rawhide-Everything': 'Fedora-Rawhide;variant=Everything'
....

When `variant` key is specified in the right-hand side of the image mapping, it is propagated to Beaker job via `distro_variant` element, to instruct Beaker to provide the given distro variant. Without the `variant` key, no `distro_variant` element is emitted.


=== AVC denials during installation

AVC denials during installation are a common issue that may appear in early development phases of development of new OS version. Beaker would mark an affected job as "failed", and, by default, Artemis would terminate the job and retry. A `ignore-avc-on-compose-pattern` key lets maintainers to specify composes for which a Beaker job may failed because of AVC denials and be still accepted.

.Specification
[source,yaml]
....
ignore-avc-on-compose-pattern: <pattern>
....

.Example
[source,yaml]
....
# AVC denials appear when installing new Fedora 55, they will be fixed next week.
# For now, let users test their components.
ignore-avc-on-compose-pattern: "(?i)fedora-55"
....


=== Installation method

With the help of `installation-method-map` key, it is possible to specify a custom installation method in the case of need. The key holds a mapping between regular expressions, matching compose/distro, and corresponding methods. If the compose/distro of a request matches one of the patterns, its method is added to Beaker job XML.

Patterns are matched against a combination of multiple guest request properties: request compose and architecture, and corresponding Beaker distro and optionally its variant, if set. All four components are separated with a colon, `:`. For example, a guest request for Fedora 55 on x86_64, mapped to `Fedora-55-20240522.0` distro, would yield the following string for patterns to match: `Fedora-55:x86_64:Fedora-55-20240522.0:Server`.

.Specification
[source,yaml]
....
installation-method-map:
  <pattern>: <string>
  <pattern>: <string>
  ...
....

.Example
[source,yaml]
....
# There is a bug in Fedora 55 installation that requires HTTP method to be used.
installation-method-map:
  "(?i)^fedora-55.*": "http"
....
