---
title: "Beaker driver"
date: 2021-12-13T23:30:02+01:00
draft: false
---
:sectlinks:
:showtitle:

== Beaker

=== Credentials

When Beaker access is protected by authentication, driver can be configured to include credentials when talking to its backend.

.Specification
[source,yaml]
....
username: <string>
password: <string>
....

.Example
[source,yaml]
....
username: a-beaker-username
password: corresponding-password
....

[NOTE]
====
Both `username` and `password` are required when any of these two is used - driver expects either no explicit credentials, or both username and password to be given.
====

=== Beaker groups

To avoid provisioning machines owned by particular Beaker groups, driver can be configured to avoid them.

.Specification
[source,yaml]
....
avoid-groups:
  - group-1
  - group-2
  ...
....

.Example
[source,yaml]
....
avoid-groups:
  # While our Beaker account has access to these groups, don't provision machines owned by them.
  - special-gpus
  - laptops
....

Each provisioning Beaker job would then contain two sets of elements to implement this behavior:

* `<group op="!=" value="$groupname"/>` to instruct Beaker to avoid this group,
* `<hostname op="!=" value="$hostname"/>` to instruct Beaker to avoid machines *owned* by these groups.

The list of machines owned by each group is cached, updated periodically by querying Beaker API.

[NOTE]
====
For more notes on how drivers query their backends, see <<drivers.adoc#_collection_of_information,"Collection of information">>.
====

[NOTE]
====
`avoid-hostnames` and `avoid-groups` are fully compatible, and can be used together.
====

[TIP]
====
It is possible to configure multiple pools for the same set of Beaker credentials, each with different `avoid-groups` list. For example:

[source,yaml]
....
# pool #1
avoid-groups:
  - laptops

# pool #2
avoid-groups:
  - generic-group-owning-machines-not-owned-by-any-other-group
....

This way, common guest requests can be routed to pool #1, while requests in the need of a special laptop HW would be routed to pool #2.
====

=== Beaker hostnames

To avoid provisioning particular machines, driver can be configured to avoid them.

.Specification
[source,yaml]
....
avoid-hostnames:
  - hostname-1
  - hostname-2
  ...
....

.Example
[source,yaml]
....
avoid-hostnames:
  # The following machines are not to be used for day-to-day jobs.
  - some.valuable.machine.com
  # This is a special laptop we do not want to use at all.
  - big-boss.foo.com
....

Each provisioning Beaker job would then contain a set of `<hostname/>` elements to instruct Beaker to avoid the listed machines.

[NOTE]
====
`avoid-hostnames` and `avoid-groups` are fully compatible, and can be used together.
====

[TIP]
====
It is possible to configure multiple pools for the same set of Beaker credentials, each with different `avoid-hostnames` list. For example:

[source,yaml]
....
# pool #1
avoid-hostnames:
  - fancy1.foo.com
  - fancy2.foo.com

# pool #2
avoid-hostnames:
  # Can use fancyN machines, but...
  - not-so-fancy1.foo.com
  - not-so-fancy2.foo.com
....
====
