---
title: "Drivers"
date: 2021-08-11T08:10:36+01:00
draft: false
---
:sectlinks:
:showtitle:

== Drivers

A driver acts on the boundary between Artemis core and a given provisioning service. By implementing basic methods like "inspect VM" or "release resources", provides necessary level of polymorphism, allowing Artemis to switch transparently between pools as needed.

=== Driver capabilities

Capabilities are features whose support is built-in into the driver. The support is usually optional, and the feature may be disabled, but it is not possible to enable feature driver does not support.

* `supports-snapshots`: the driver can handle snapshots of some kind.
* `supports-spot-instances`: the driver can handle spot instance requests.
* `supports-native-post-install-script`: the driver can handle the post-installation script on its own. Artemis core will execute the script in the preparation stage for drivers that do no have this capability.
* `supported-guest-logs`: list of log name/log content type pairs describing what logs are supported by the driver.

[%header,cols="1,1,1,1,1"]
|===
|Driver
|supports-snapshots
|supports-spot-instances
|supports-native-post-install-script
|supported-guest-logs

|`aws`
|[red]#no#
|[green]#yes#
|[green]#yes#
|console/blob

|`azure`
|[red]#no#
|[red]#no#
|[green]#yes#
|-

|`beaker`
|[red]#no#
|[red]#no#
|[red]#no#
|-

|`localhost`
|[red]#no#
|[red]#no#
|[red]#no#
|-

|`openstack`
|[green]#yes#
|[red]#no#
|[green]#yes#
|console/blob
console/URL

|===


=== HW requirements

A guest request can specify various HW constraints the provisioned machines must satisfy. For example, a desired number of CPU cores or a minimal root disk size. These constraints are eventually used by drivers to find - or create - suitable guests. Unfortnatelly, not all drivers are capable of handling all possible HW requirements, limitations may apply.

[NOTE]
====
The table below describe the built-in support for various features. However, to actually support a given feature, a maintainer may need to provide additional configuration. Such requirements are marked with an asterisk (`*`).
====

[%header,cols="1,1,1,1,1,1"]
|===
|HW constraint
|`aws`
|`azure`
|`beaker`
|`localhost`
|`openstack`

|`arch`
|[green]#yes#
|[green]#yes#
|[green]#yes#
|[green]#yes#
|[green]#yes#

|`cpu.cores`
|[green]#yes#
|[red]#no#
|[green]#yes#
|[red]#no#
|[green]#yes#

|`cpu.family`
|[green]#yes# *
|[red]#no#
|[red]#no#
|[red]#no#
|[green]#yes# *

|`cpu.family_name`
|[green]#yes# *
|[red]#no#
|[red]#no#
|[red]#no#
|[green]#yes# *

|`cpu.model`
|[green]#yes# *
|[red]#no#
|[green]#yes# *
|[red]#no#
|[green]#yes# *

|`cpu.model_name`
|[green]#yes# *
|[red]#no#
|[green]#yes# *
|[red]#no#
|[green]#yes# *

|`cpu.processors`
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#

|`disk[].space`
|[yellow]#partial# See <<hw-notes-only-one-disk, #1>>. *
|[red]#no#
|[yellow]#partial# See <<hw-notes-only-one-disk, #1>>.
|[red]#no#
|[yellow]#partial# See <<hw-notes-only-one-disk, #1>>.

|`memory`
|[green]#yes#
|[red]#no#
|[green]#yes#
|[red]#no#
|[green]#yes#

|`virtualization.hypervisor`
|[green]#yes#
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#

|`virtualization.is_supported`
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#

|`virtualization.is_virtualized`
|[green]#yes#
|[red]#no#
|[red]#no#
|[red]#no#
|[red]#no#

|===

1. [[hw-notes-only-one-disk]]`disk[]` supports only 1 item.
