apiVersion: v1
kind: Service
metadata:
  name: {{ template "artemis.api.fullname" . }}
  labels:
    app.kubernetes.io/app: {{ template "artemis.fullname" . }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/app: {{ template "artemis.fullname" . }}
    app.kubernetes.io/component: api
  ports:
  - name: {{ template "artemis.api.fullname" . }}
    port: {{ template "artemis.api.port" . }}
    targetPort: 8001
