$schema: http://json-schema.org/draft-07/schema#
description: Environment schema
type: object

definitions:

  # HW requirements: `boot` block
  hw_boot:
    type: object

    properties:
      method:
        type: string
        enum:
          - bios
          - uefi

    additionalProperties: false

    # enforce at least one property - we don't care which one, but we don't want
    # empty `boot`.
    minProperties: 1

  # HW requirements: `cpu` block
  hw_cpu:
    type: object

    properties:
      processors:
        anyOf:
          - type: string
          - type: integer
      cores:
        anyOf:
          - type: string
          - type: integer
      family:
        anyOf:
          - type: string
          - type: integer
      model:
        anyOf:
          - type: string
          - type: integer
      model_name:
        type: string

    additionalProperties: false

    # enforce at least one property - we don't care which one, but we don't want
    # empty `cpu`.
    minProperties: 1

  # HW requirements: single `disk` item
  hw_disk:
    type: object

    properties:
      size:
        anyOf:
          - type: string
          - type: integer

    additionalProperties: false

    # enforce at least one property - we don't care which one, but we don't want
    # empty `disk`.
    minProperties: 1

  # HW requirements: `disk` block
  hw_disks:
    type: array
    items:
      "$ref": "#/definitions/hw_disk"

  # HW requirements: single `network` item
  hw_network:
    type: object

    properties:
      type:
        type: string

    additionalProperties: false

    # enforce at least one property - we don't care which one, but we don't want
    # empty `network`.
    minProperties: 1

  # HW requirements: `network` block
  hw_networks:
    type: array
    items:
      "$ref": "#/definitions/hw_network"

  # HW requirements: basic block
  hw_block:
    type: object

    properties:
      memory:
        anyOf:
          - type: string
          - type: integer

      boot:
        "$ref": "#/definitions/hw_boot"

      cpu:
        "$ref": "#/definitions/hw_cpu"

      disk:
        "$ref": "#/definitions/hw_disks"

      network:
        "$ref": "#/definitions/hw_networks"

    additionalProperties: false

    # enforce at least one property - we don't care which one, but we don't want
    # empty `block`.
    minProperties: 1

  # HW requirements: conditions
  hw_and:
    type: object
    properties:
      "and":
        type: array
        items:
          anyOf:
            - "$ref": "#/definitions/hw_boot"
            - "$ref": "#/definitions/hw_cpu"
            - "$ref": "#/definitions/hw_disks"
            - "$ref": "#/definitions/hw_networks"
            - "$ref": "#/definitions/hw_block"
            - "$ref": "#/definitions/hw_and"
            - "$ref": "#/definitions/hw_or"

    required:
      - "and"

  hw_or:
    type: object
    properties:
      "or":
        type: array
        items:
          anyOf:
            - "$ref": "#/definitions/hw_boot"
            - "$ref": "#/definitions/hw_cpu"
            - "$ref": "#/definitions/hw_disks"
            - "$ref": "#/definitions/hw_networks"
            - "$ref": "#/definitions/hw_block"
            - "$ref": "#/definitions/hw_and"
            - "$ref": "#/definitions/hw_or"

    required:
      - "or"

  hw_constraints:
    anyOf:
      - "$ref": "#/definitions/hw_boot"
      - "$ref": "#/definitions/hw_cpu"
      - "$ref": "#/definitions/hw_disks"
      - "$ref": "#/definitions/hw_networks"
      - "$ref": "#/definitions/hw_block"
      - "$ref": "#/definitions/hw_and"
      - "$ref": "#/definitions/hw_or"

    required: []

  hw_requirements:
    type: object

    properties:
      arch:
        type: string

      constraints:
        "$ref": "#/definitions/hw_constraints"

    required:
      - arch

  os_requirements:
    type: object

    properties:
      compose:
        type: string

    required:
      - compose

    additionalProperties: false

properties:
  hw:
    "$ref": "#/definitions/hw_requirements"

  os:
    "$ref": "#/definitions/os_requirements"

  pool:
    anyOf:
      - type:
        - string
      - type:
        - "null"
    default: null

  snapshots:
    type: boolean
    default: false

  spot_instance:
    anyOf:
      - type:
        - boolean
      - type:
        - "null"
    default: null

required:
  - hw
  - os

additionalProperties: false
