$schema: http://json-schema.org/draft-07/schema#
description: Environment schema
type: object

definitions:
  hw_requirements:
    type: object

    properties:
      arch:
        type: string

    required:
      - arch

    additionalProperties: true

  os_requirements:
    type: object

    properties:
      compose:
        type: string

    required:
      - compose

    additionalProperties: false

properties:
  arch:
    type: string

  hw:
    "$ref": "#/definitions/hw_requirements"

  os:
    "$ref": "#/definitions/os_requirements"

  pool:
    anyOf:
      - type:
        - string
      - type:
        - "null"
    default: null

  snapshots:
    type: boolean
    default: false

  spot_instance:
    anyOf:
      - type:
        - boolean
      - type:
        - "null"
    default: null

required:
  # - arch
  - os
  - hw

additionalProperties: false
