apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{ include "adminer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "adminer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{ include "adminer.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: {{ .Chart.Name }}
          image: >-
            {{
              include "common.images.image" (
                  dict "imageRoot" .Values.image
                  "global" .Values.global
                )
            }}
          imagePullPolicy: {{ default "" .Values.image.pullPolicy }}
          env:
            {{- if .Values.extraEnv }}
            {{
              include "common.tplvalues.render"
                (dict "value" .Values.extraEnv "context" $) |
              nindent 12
            }}
            {{- end }}
            - name: ADMINER_DEFAULT_SERVER
              value: {{ template "adminer.defaultServer" . }}
            - name: ADMINER_DESIGN
              value: pepa-linha
          ports:
            - name: adminer-http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
