apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{ include "adminer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: adminer-http
      protocol: TCP
      name: adminer-http
  selector:
    {{ include "adminer.selectorLabels" . | nindent 4 }}
